# -*- coding: utf-8 -*-
"""Proximity Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TA8wqCot2LbLShYQH-uBKIOXT10IYH0
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
collisions = pd.read_csv("/content/drive/My Drive/UofT/Third Year/Fall/MIE368 Project - Group 15/Code/collisions_dataset/collisions_enriched.csv")
speed_cameras = pd.read_csv("/content/drive/My Drive/UofT/Third Year/Fall/MIE368 Project - Group 15/Code/speed_camera_dataset/speed_cameras_clean.csv")

collisions[['lat', 'lon']].head()

speed_cameras[['lat', 'lon']].head()

!pip install haversine

from haversine import haversine, Unit
import folium
import seaborn as sns
import matplotlib.pyplot as plt

camera_coords = list(zip(speed_cameras['lat'], speed_cameras['lon']))

def nearest_camera_distance(collision_point):
    distances = [haversine(collision_point, cam, unit=Unit.METERS) for cam in camera_coords]
    return min(distances)

collisions['nearest_camera_dist_m'] = collisions.apply(
    lambda row: nearest_camera_distance((row['lat'], row['lon'])),
    axis=1
)

buffer = 500  # metres
collisions['distance_category'] = collisions['nearest_camera_dist_m'].apply(
    lambda d: 'Near' if d <= buffer else 'Far'
)

sns.countplot(x='distance_category', data=collisions, palette=['green', 'red'])
plt.title("Collisions by Distance to Nearest Speed Camera")
plt.xlabel("Distance Category")
plt.ylabel("Number of Collisions")
plt.show()